### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by sahinsrhn** [object-x/CS240#1]
Hi Abdulvahap,

First of all well done good codes, the thing i just only want is run your each codes in one cell and show its result because i want to see each codes result if you put all codes in one cell ipython always shows the last print result and others will not be showed. And other thing is also can you write your name and surname to your readme file that makes easy to recognize you for me

**Comment by ammoti** [comment]
Thank you,
I have updated code. But in my version each code(each question) in different cell, and also you can see "out line" each end of line.
